import Link from 'next/link';
import type { Metadata } from "next";
import "./globals.css";
import styles from './styles/Layout.module.css';
import Navigation from './components/Navigation';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <header className={styles.header}>
        <Navigation />
      </header>
      <main className={styles.main}>{children}</main>
    </body>
  </html>
  );
}
